# Generated by Django 5.1.2 on 2024-10-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
