# Generated by Django 5.1.2 on 2024-10-15 02:52

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_membership_type_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.aadhar_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.pan_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_pic_upload_to),
        ),
    ]
